{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "kctc7fra7bfxpas4f2l2sq2fy4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.0.jar",
          "url": "runescape-api-3.3.0.jar",
          "size": 103468,
          "sha512": "2e3d37071d3bf5641f45dd9910d6a703b229d6f16e48cb5ef6ec37e925ceaa137ae3b02a199b7f6898d7c6f0d6b476389170d01fca2d4d4e8268fa554bb59c81",
          "sha256": "bfd761f9d1b5c58fbad7a46d77940c5cbfaf6b75d7ed71452d83b01da3b771bf",
          "sha1": "ba9d6a036880a4137c4b62a0ebc45e1635baf114",
          "md5": "df2b22fc93af6d79e31bc6bf49f33975"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.0.jar",
          "url": "runescape-api-3.3.0.jar",
          "size": 103468,
          "sha512": "2e3d37071d3bf5641f45dd9910d6a703b229d6f16e48cb5ef6ec37e925ceaa137ae3b02a199b7f6898d7c6f0d6b476389170d01fca2d4d4e8268fa554bb59c81",
          "sha256": "bfd761f9d1b5c58fbad7a46d77940c5cbfaf6b75d7ed71452d83b01da3b771bf",
          "sha1": "ba9d6a036880a4137c4b62a0ebc45e1635baf114",
          "md5": "df2b22fc93af6d79e31bc6bf49f33975"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.0-sources.jar",
          "url": "runescape-api-3.3.0-sources.jar",
          "size": 99524,
          "sha512": "b1193ffa6fe3fe40b95214e9eca89c79366d7d1ba87870a5eb9278744d28cf531ade75a8f2944660e7126d7ed6f7d8913ce3888ed0d4c0bb8292ca8cd6343dd2",
          "sha256": "ba714108344a746ac27c8bacd5881a143f3ef2462834c78c3809d73de139d439",
          "sha1": "c3f81d8b3149f27f7df5e1a260ba81935feb1d37",
          "md5": "847d305c4519491ca39e20b8d883f26a"
        }
      ]
    }
  ]
}
