{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "n5tliixa6rhi7p44b3y6j2dkea"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.0.jar",
          "url": "runescape-api-3.3.0.jar",
          "size": 103468,
          "sha512": "66fecc4547b07f4d7f1c50f36e0af54108649fb18bace0264688d709c4f3e6d65dc18a500d6d61acf17c59cef4e8dbe5782ff873c6c74e852e1c700b8408d670",
          "sha256": "176c30a61fca36a0b44dc7c1983d713df39ef3784885cc3c8d3bc91cb962d4e3",
          "sha1": "65c6736599ad1fdf01c02ce20a571f7ce2ebaa88",
          "md5": "aeff47f125ecf1eb4b88907aadc75464"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.3.0.jar",
          "url": "runescape-api-3.3.0.jar",
          "size": 103468,
          "sha512": "66fecc4547b07f4d7f1c50f36e0af54108649fb18bace0264688d709c4f3e6d65dc18a500d6d61acf17c59cef4e8dbe5782ff873c6c74e852e1c700b8408d670",
          "sha256": "176c30a61fca36a0b44dc7c1983d713df39ef3784885cc3c8d3bc91cb962d4e3",
          "sha1": "65c6736599ad1fdf01c02ce20a571f7ce2ebaa88",
          "md5": "aeff47f125ecf1eb4b88907aadc75464"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescape-api-3.3.0-sources.jar",
          "url": "runescape-api-3.3.0-sources.jar",
          "size": 99524,
          "sha512": "d2102ed6f1d4bc5232be8142fd9521403415e162d1f938d8526d3380824d8edef16ee40d5af50ef59433c80a2b3f3875786500252f2aa11e9590c1249fe4b485",
          "sha256": "e6b06563b558d5428f54a3bee1e19674e24de4fb1915160cd942a75f7f4eccc5",
          "sha1": "792cc2f322638998571e2147048b92e8b94ebe39",
          "md5": "e4ee2c987b193b0b4be361c8ea129923"
        }
      ]
    }
  ]
}
