{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "n5tliixa6rhi7p44b3y6j2dkea"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "7067ad29adbc82968262dddc7bfe6e1c7c0147dd78fbbd6dfe512ac64ad558a8c9cf27ead016150a0bea87d5ec9361f62a5b0f5a9287d86f9a1db0ede7c5e295",
          "sha256": "cf710f6be9b7b5863a44817b13acb3593351c3b79afceed4cbe8809915a56b7e",
          "sha1": "8e504f50bd75ee85167aab5907361c4d5254e41f",
          "md5": "311ef19e4a9a4acaa88f8b26a786de26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "7067ad29adbc82968262dddc7bfe6e1c7c0147dd78fbbd6dfe512ac64ad558a8c9cf27ead016150a0bea87d5ec9361f62a5b0f5a9287d86f9a1db0ede7c5e295",
          "sha256": "cf710f6be9b7b5863a44817b13acb3593351c3b79afceed4cbe8809915a56b7e",
          "sha1": "8e504f50bd75ee85167aab5907361c4d5254e41f",
          "md5": "311ef19e4a9a4acaa88f8b26a786de26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.0-sources.jar",
          "url": "injected-client-3.3.0-sources.jar",
          "size": 261,
          "sha512": "e60535baa3be5448e578a5e5011fb8701bd805a0a5384d4420bd76432f6519265a3cbe23684a8b80cdcca666303e4be27cb39b818915b98f93f373a26ad89330",
          "sha256": "222f03cc2f080dd47ab513f5a9515b2c8da9bb9213bea9bb8d2de0b520bd1991",
          "sha1": "cd324cd78d64917d50c160d2c832e5aeda5a8301",
          "md5": "61e8dc307209f580c4d793391459a9f1"
        },
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "7067ad29adbc82968262dddc7bfe6e1c7c0147dd78fbbd6dfe512ac64ad558a8c9cf27ead016150a0bea87d5ec9361f62a5b0f5a9287d86f9a1db0ede7c5e295",
          "sha256": "cf710f6be9b7b5863a44817b13acb3593351c3b79afceed4cbe8809915a56b7e",
          "sha1": "8e504f50bd75ee85167aab5907361c4d5254e41f",
          "md5": "311ef19e4a9a4acaa88f8b26a786de26"
        }
      ]
    }
  ]
}
