{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "kctc7fra7bfxpas4f2l2sq2fy4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "764e20e7503351f45c887cdf7022db668e58f20f08cc398d1369f9d4a8499ad58fec683d84850d5edde95ebd1a9fe3149380a6db7c47fdf01d9f9a1ac24d318e",
          "sha256": "0686d1aa53a05e06cdc1d6575d3a720607b92961e2ca94d099dc3a0bd37a50bd",
          "sha1": "61d0457c42dc101f0b68ddb98bc1308f376b60e5",
          "md5": "76ba75041c468bf115b0818755703d18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "764e20e7503351f45c887cdf7022db668e58f20f08cc398d1369f9d4a8499ad58fec683d84850d5edde95ebd1a9fe3149380a6db7c47fdf01d9f9a1ac24d318e",
          "sha256": "0686d1aa53a05e06cdc1d6575d3a720607b92961e2ca94d099dc3a0bd37a50bd",
          "sha1": "61d0457c42dc101f0b68ddb98bc1308f376b60e5",
          "md5": "76ba75041c468bf115b0818755703d18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.3.0-sources.jar",
          "url": "injected-client-3.3.0-sources.jar",
          "size": 261,
          "sha512": "73936ebefd56b0a6d3c6eb5267cd0337ee436aa3bb1e8166015f5f1e69f90b43b32dc67215311d7039e68030fad5b42bdae97833b1f08915cb7c45bf68d3416f",
          "sha256": "5cf54838b657f57349172dec9c7837c9ac0aeca496d19b15af8d92e6e7b2ef9f",
          "sha1": "adee6fda5386abf93e52259186d4e5515ad88939",
          "md5": "ffbfa859d8eb2dba5b75d2d45a405e4c"
        },
        {
          "name": "injected-client-3.3.0.jar",
          "url": "injected-client-3.3.0.jar",
          "size": 2252595,
          "sha512": "764e20e7503351f45c887cdf7022db668e58f20f08cc398d1369f9d4a8499ad58fec683d84850d5edde95ebd1a9fe3149380a6db7c47fdf01d9f9a1ac24d318e",
          "sha256": "0686d1aa53a05e06cdc1d6575d3a720607b92961e2ca94d099dc3a0bd37a50bd",
          "sha1": "61d0457c42dc101f0b68ddb98bc1308f376b60e5",
          "md5": "76ba75041c468bf115b0818755703d18"
        }
      ]
    }
  ]
}
