{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "n5tliixa6rhi7p44b3y6j2dkea"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.0.jar",
          "url": "http-api-3.3.0.jar",
          "size": 164004,
          "sha512": "2eda9a00e1afd532dc82d49dfa9c816ca1fb2d3b1c9eca274525e20f2c7ba8e245f73a2d0a3cbfdbb3ae68e490b21df7d50da0a5c53a91fff9e43320b6e63ae2",
          "sha256": "d9d7807e0ea0df49f7554b35d41c151166cbdf20dfb6846421769faa5f2a8f65",
          "sha1": "1b2f05e959956efee59420074103ed6e0346882f",
          "md5": "b8dad96d66a12a58943fded54c4d61e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.0.jar",
          "url": "http-api-3.3.0.jar",
          "size": 164004,
          "sha512": "2eda9a00e1afd532dc82d49dfa9c816ca1fb2d3b1c9eca274525e20f2c7ba8e245f73a2d0a3cbfdbb3ae68e490b21df7d50da0a5c53a91fff9e43320b6e63ae2",
          "sha256": "d9d7807e0ea0df49f7554b35d41c151166cbdf20dfb6846421769faa5f2a8f65",
          "sha1": "1b2f05e959956efee59420074103ed6e0346882f",
          "md5": "b8dad96d66a12a58943fded54c4d61e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.0-sources.jar",
          "url": "http-api-3.3.0-sources.jar",
          "size": 107148,
          "sha512": "c82a4ef6f204ad16e35493c9878874a5197eb330fedbb301be8fa309438cbd23f3845a7cf14d75248be270365ed22e9b30a222d90c5cab45efa37ac1162202a8",
          "sha256": "b3cde0e4303414c1011e04723b2018b249bec53770f5a30553eadef97e4bcd4d",
          "sha1": "4f00027035917bc9b16967a4937273b59050965a",
          "md5": "dc3ef22d5724daf7f2ad2e7f5871f4cc"
        }
      ]
    }
  ]
}
