{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "hn6zrs5v2zdppi5uo6bg4usdeq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.3.0.jar",
          "url": "http-api-3.3.0.jar",
          "size": 164003,
          "sha512": "1d1743b97fcae39d9bc832f891609c9bc93dd7e2fc8611499bbfc8c4b1b9a24bb78a44afb977b2fb187df0dc6e38445db65bbabdbc32b885505b325a82444f45",
          "sha256": "322622f28baeaf645da6c6844b3381645827a91877649a88b429fb44f05d300d",
          "sha1": "6b240bb5ccd1517acfeb0accd3c328aec74f2e50",
          "md5": "d50b4890d9ccfab90849b2c7b6f3a698"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.3.0.jar",
          "url": "http-api-3.3.0.jar",
          "size": 164003,
          "sha512": "1d1743b97fcae39d9bc832f891609c9bc93dd7e2fc8611499bbfc8c4b1b9a24bb78a44afb977b2fb187df0dc6e38445db65bbabdbc32b885505b325a82444f45",
          "sha256": "322622f28baeaf645da6c6844b3381645827a91877649a88b429fb44f05d300d",
          "sha1": "6b240bb5ccd1517acfeb0accd3c328aec74f2e50",
          "md5": "d50b4890d9ccfab90849b2c7b6f3a698"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "http-api-3.3.0-sources.jar",
          "url": "http-api-3.3.0-sources.jar",
          "size": 107148,
          "sha512": "1269103ef58211b391d81ce6afb6589a857613b2d00e9ee75e68afc4529c036e5fd0ed04ed38ec89ae61139c0f98d910011195027e2c9706060a4adb995ae904",
          "sha256": "0394dcf6f08cf27a68e0e05f80ec509af80c0e69f7a212c436b50a1f0a71da06",
          "sha1": "451227b118f6b5a4dfe1289e92ffcb036d86a0d1",
          "md5": "124cf470325fe7747e6275280dc9fb23"
        }
      ]
    }
  ]
}
