{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "n5tliixa6rhi7p44b3y6j2dkea"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.0.jar",
          "url": "runelite-api-3.3.0.jar",
          "size": 1179684,
          "sha512": "5081518e2efc0f6fac905aa8ad22fd140da7debbb4733c9fa57ed708530c071a610e67cc78e196f9b8b74d094b60c55c90006fa7ed189eb37ffda27524f45f02",
          "sha256": "cb6408f6b072bef5ae4840e1854ca6e7cd92c8daae77b7fad2f127fce1554b9b",
          "sha1": "3a715ce873a5eddf613f415a11be119c3dad1f6d",
          "md5": "756394f5f344f7cc23d918e809024db2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.0.jar",
          "url": "runelite-api-3.3.0.jar",
          "size": 1179684,
          "sha512": "5081518e2efc0f6fac905aa8ad22fd140da7debbb4733c9fa57ed708530c071a610e67cc78e196f9b8b74d094b60c55c90006fa7ed189eb37ffda27524f45f02",
          "sha256": "cb6408f6b072bef5ae4840e1854ca6e7cd92c8daae77b7fad2f127fce1554b9b",
          "sha1": "3a715ce873a5eddf613f415a11be119c3dad1f6d",
          "md5": "756394f5f344f7cc23d918e809024db2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.0-sources.jar",
          "url": "runelite-api-3.3.0-sources.jar",
          "size": 865215,
          "sha512": "c65217361c50a8ed2bf97a5133b9b56b1da5bb2e7ead738f90ba3ed44c8c67f3d972c2c574cf660664f81fcc321fde808b136084ccf700c9317815157aa39382",
          "sha256": "aa98b53770f5ed7f844f221a0d106d37da18db57413bf9e2d979b04bffadd137",
          "sha1": "28e979b70b6366a144fd20fceb883c173cd788d3",
          "md5": "d662f4ef429897a86149cc2e918bc6c0"
        }
      ]
    }
  ]
}
