{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "hn6zrs5v2zdppi5uo6bg4usdeq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.3.0.jar",
          "url": "runelite-api-3.3.0.jar",
          "size": 1179684,
          "sha512": "5c44f85727c3dae5585f502a8e7235d6995900d65bf2ae1fa89c0a927dfcdb1f54e40f3c018f493e698759698e40a9f434fd6e888816ed27587142d1bf7fc1a5",
          "sha256": "defc25e7a6a629f5e0af97cd0f37723d9ccd5f2782ef2622c45c9a478e9e628a",
          "sha1": "37f46d9017c1570b175d496a269d319d387882da",
          "md5": "c49fbc0074f4e89f9feb71442c8f6ae2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.3.0.jar",
          "url": "runelite-api-3.3.0.jar",
          "size": 1179684,
          "sha512": "5c44f85727c3dae5585f502a8e7235d6995900d65bf2ae1fa89c0a927dfcdb1f54e40f3c018f493e698759698e40a9f434fd6e888816ed27587142d1bf7fc1a5",
          "sha256": "defc25e7a6a629f5e0af97cd0f37723d9ccd5f2782ef2622c45c9a478e9e628a",
          "sha1": "37f46d9017c1570b175d496a269d319d387882da",
          "md5": "c49fbc0074f4e89f9feb71442c8f6ae2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-api-3.3.0-sources.jar",
          "url": "runelite-api-3.3.0-sources.jar",
          "size": 865215,
          "sha512": "7ac7e98cbacec9ab4cb16f6b5fa6b3b4588505c05e9f4b0e05ff0eaa59fd9b17780a8b29d9379fdc458acd069ec50bce82d62b7da11a1b28569a5af3f7a4a8c7",
          "sha256": "7e115aa192031398b307c552d5fd4b383bd96c57169638a13b7b44efd9c4d02d",
          "sha1": "08aadf2f46f9d14a51c0883c73d9f94edb804af1",
          "md5": "3cc3e6da22bac126093b9ea05ce6aacc"
        }
      ]
    }
  ]
}
